{"name": "Ошибка при авторизации с неверным логином и паролем", "status": "passed", "start": 1718961930297, "stop": 1718961931201, "uuid": "1feda174-c69d-416a-a765-1dc4d82c2508", "historyId": "7ac1311b194a9e37c2cf50f2e37e5e29", "testCaseId": "7ac1311b194a9e37c2cf50f2e37e5e29", "fullName": "tests.test_login_user.TestLoginUser#test_user_login_incorrect_login_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-G789T9B"}, {"name": "thread", "value": "8228-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}