{"name": "Ошибка при получении заказа неавторизованным пользователем", "status": "passed", "start": 1718967222692, "stop": 1718967223479, "uuid": "587da2d3-88f6-4a66-994d-8de687d2cab5", "historyId": "5baaf3849fcbd18ae3901d4f3f63afcf", "testCaseId": "5baaf3849fcbd18ae3901d4f3f63afcf", "fullName": "tests.test_get_order.TestGetOrder#test_get_order_user_without_authorisation_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-G789T9B"}, {"name": "thread", "value": "10008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}