{"name": "Ошибка при авторизации с неверным логином и паролем", "status": "passed", "start": 1718826696046, "stop": 1718826696846, "uuid": "38c7cb8f-4299-47d0-972f-529cb874cccb", "historyId": "7ac1311b194a9e37c2cf50f2e37e5e29", "testCaseId": "7ac1311b194a9e37c2cf50f2e37e5e29", "fullName": "tests.test_login_user.TestLoginUser#test_user_login_incorrect_login_data_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-G789T9B"}, {"name": "thread", "value": "17000-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}